version: '3.8'

services:
  # Service 1: Your high-performance PyTorch backend engine
  backend:
    build: .
    image: sketch-gpu-engine
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      # 👇 Bridge 1: The Images
      - C:\Users\Lokesh\Desktop\Sketch-DevOps-Project\trainB:/app/trainB
      # 👇 Bridge 2: The AI Weights
      - C:\Users\Lokesh\Desktop\Sketch-DevOps-Project\phase2_weights_chair\ckpt_epoch_80.pth:/app/phase2_weights_chair/ckpt_epoch_80.pth
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
  
  # Service 2: Your new visual web dashboard
  frontend:
    image: python:3.10-slim
    working_dir: /app
    command: sh -c "pip install streamlit requests Pillow && streamlit run ui.py --server.port=8501 --server.address=0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - .:/app
      # 👇 Bridge 3: Frontend needs the images so it can show them to you on the screen!
      - C:\Users\Lokesh\Desktop\Sketch-DevOps-Project\trainB:/app/trainB